/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "crd/pkg/apis/crd/v1alpha1"
	scheme "crd/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomPodsGetter has a method to return a CustomPodInterface.
// A group's client should implement this interface.
type CustomPodsGetter interface {
	CustomPods(namespace string) CustomPodInterface
}

// CustomPodInterface has methods to work with CustomPod resources.
type CustomPodInterface interface {
	Create(*v1alpha1.CustomPod) (*v1alpha1.CustomPod, error)
	Update(*v1alpha1.CustomPod) (*v1alpha1.CustomPod, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CustomPod, error)
	List(opts v1.ListOptions) (*v1alpha1.CustomPodList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomPod, err error)
	CustomPodExpansion
}

// customPods implements CustomPodInterface
type customPods struct {
	client rest.Interface
	ns     string
}

// newCustomPods returns a CustomPods
func newCustomPods(c *CrdV1alpha1Client, namespace string) *customPods {
	return &customPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customPod, and returns the corresponding customPod object, and an error if there is any.
func (c *customPods) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomPod, err error) {
	result = &v1alpha1.CustomPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("custompods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomPods that match those selectors.
func (c *customPods) List(opts v1.ListOptions) (result *v1alpha1.CustomPodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("custompods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customPods.
func (c *customPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("custompods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customPod and creates it.  Returns the server's representation of the customPod, and an error, if there is any.
func (c *customPods) Create(customPod *v1alpha1.CustomPod) (result *v1alpha1.CustomPod, err error) {
	result = &v1alpha1.CustomPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("custompods").
		Body(customPod).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customPod and updates it. Returns the server's representation of the customPod, and an error, if there is any.
func (c *customPods) Update(customPod *v1alpha1.CustomPod) (result *v1alpha1.CustomPod, err error) {
	result = &v1alpha1.CustomPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("custompods").
		Name(customPod.Name).
		Body(customPod).
		Do().
		Into(result)
	return
}

// Delete takes name of the customPod and deletes it. Returns an error if one occurs.
func (c *customPods) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("custompods").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("custompods").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customPod.
func (c *customPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomPod, err error) {
	result = &v1alpha1.CustomPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("custompods").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
