/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	versioned "crd/pkg/client/clientset/versioned"
	internalinterfaces "crd/pkg/client/informers/externalversions/internalinterfaces"
	time "time"

	crdcomv1alpha1 "crd/pkg/apis/crd.com/v1alpha1"
	v1alpha1 "crd/pkg/client/listers/crd.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomPodInformer provides access to a shared informer and lister for
// CustomPods.
type CustomPodInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CustomPodLister
}

type customPodInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomPodInformer constructs a new informer for CustomPod type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomPodInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomPodInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomPodInformer constructs a new informer for CustomPod type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomPodInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().CustomPods(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().CustomPods(namespace).Watch(options)
			},
		},
		&crdcomv1alpha1.CustomPod{},
		resyncPeriod,
		indexers,
	)
}

func (f *customPodInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomPodInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customPodInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdcomv1alpha1.CustomPod{}, f.defaultInformer)
}

func (f *customPodInformer) Lister() v1alpha1.CustomPodLister {
	return v1alpha1.NewCustomPodLister(f.Informer().GetIndexer())
}
